import { ProductType } from "@/schemas/productSchema"

export const exampleProductsData: ProductType[] = [
  {
    productId: "p001",
    category: "rau-cu",
    supplier: "Công ty Nông sản Xanh",
    productName: "Cải Bó Xôi",
    slug: "cai-bo-xoi-yk8pgx",
    description: "Cải bó xôi sạch, không sử dụng hóa chất, tốt cho sức khỏe.",
    price: 25000,
    stock: 150,
    weight: 0.5,
    unit: "kg",
    origin: "Đà Lạt",
    organic: true,
    images: ["https://placehold.jp/250x192.png"],
    status: true,
    entryDate: "2024-09-25",
    expiryDate: "2024-10-10",
    createdAt: "2024-09-25",
    createdBy: "asd",
    updatedAt: "2024-09-25",
    updatedBy: "asd"
  },
  {
    productId: "p002",
    category: "rau-cu",
    supplier: "Trang Trại Việt Hưng",
    productName: "Rau Muống",
    slug: "rau-muong-z3ko4p",
    description: "Rau muống tươi, giàu chất xơ, sản phẩm sạch từ nông trại.",
    price: 18000,
    stock: 100,
    weight: 0.5,
    unit: "kg",
    origin: "Hà Nam",
    organic: true,
    images: ["https://placehold.jp/250x192.png"],
    status: true,
    entryDate: "2024-09-20",
    expiryDate: "2024-09-28",
    createdAt: "2024-09-20",
    createdBy: "asd",
    updatedAt: "2024-09-20",
    updatedBy: "asd"
  },
  {
    productId: "p003",
    category: "rau-cu",
    supplier: "Nông Trại Xanh",
    productName: "Khoai Tây",
    slug: "khoai-tay-okce88",
    description: "Khoai tây sạch, phù hợp để làm nhiều món ăn ngon.",
    price: 30000,
    stock: 200,
    weight: 1,
    unit: "kg",
    origin: "Sơn La",
    organic: true,
    images: ["https://placehold.jp/250x192.png"],
    status: true,
    entryDate: "2024-09-24",
    expiryDate: "2024-10-10",
    createdAt: "2024-09-24",
    createdBy: "asd",
    updatedAt: "2024-09-24",
    updatedBy: "asd"
  },
  {
    productId: "p004",
    category: "trai-cay",
    supplier: "Hợp tác xã Nông sản Việt",
    productName: "Táo Mèo",
    slug: "tao-meo-zd26k5",
    description: "Táo mèo tươi, được trồng tự nhiên tại vùng cao Tây Bắc.",
    price: 50000,
    stock: 50,
    weight: 1,
    unit: "kg",
    origin: "Tây Bắc",
    organic: true,
    images: ["https://placehold.jp/250x192.png"],
    status: true,
    entryDate: "2024-09-23",
    expiryDate: "2024-10-05",
    createdAt: "2024-09-23",
    createdBy: "asd",
    updatedAt: "2024-09-23",
    updatedBy: "asd"
  },
  {
    productId: "p005",
    category: "rau-cu",
    supplier: "Công Ty Rau Sạch Việt",
    productName: "Rau Dền Đỏ",
    slug: "rau-den-do-7ujuqv",
    description: "Rau dền đỏ chứa nhiều vitamin, sản phẩm hữu cơ.",
    price: 22000,
    stock: 120,
    weight: 0.5,
    unit: "kg",
    origin: "Đà Lạt",
    organic: true,
    images: ["https://placehold.jp/250x192.png"],
    status: true,
    entryDate: "2024-09-22",
    expiryDate: "2024-10-05",
    createdAt: "2024-09-22",
    createdBy: "asd",
    updatedAt: "2024-09-22",
    updatedBy: "asd"
  },
  {
    productId: "p006",
    category: "rau-cu",
    supplier: "Trang Trại Đồng Quê",
    productName: "Cà Rốt",
    slug: "ca-rot-dexyv7",
    description: "Cà rốt hữu cơ, giàu beta-carotene, tốt cho sức khỏe mắt.",
    price: 28000,
    stock: 180,
    weight: 1,
    unit: "kg",
    origin: "Ninh Thuận",
    organic: true,
    images: ["https://placehold.jp/250x192.png"],
    status: true,
    entryDate: "2024-09-21",
    expiryDate: "2024-10-05",
    createdAt: "2024-09-21",
    createdBy: "asd",
    updatedAt: "2024-09-21",
    updatedBy: "asd"
  },
  {
    productId: "p007",
    category: "trai-cay",
    supplier: "Trang Trại Trái Cây Sạch",
    productName: "Xoài Cát",
    slug: "xoai-cat-uju54f",
    description: "Xoài cát ngọt, không thuốc bảo vệ thực vật, an toàn.",
    price: 45000,
    stock: 80,
    weight: 1,
    unit: "kg",
    origin: "Tiền Giang",
    organic: true,
    images: ["https://placehold.jp/250x192.png"],
    status: true,
    entryDate: "2024-09-26",
    expiryDate: "2024-10-10",
    createdAt: "2024-09-26",
    createdBy: "asd",
    updatedAt: "2024-09-26",
    updatedBy: "asd"
  },
  {
    productId: "p008",
    category: "qua",
    supplier: "Nông trại Hữu Cơ Việt",
    productName: "Cà Chua",
    slug: "ca-chua-v6jvre",
    description: "Cà chua đỏ tươi, giàu vitamin C, không thuốc trừ sâu.",
    price: 35000,
    stock: 60,
    weight: 1,
    unit: "kg",
    origin: "Lâm Đồng",
    organic: true,
    images: ["https://placehold.jp/250x192.png"],
    status: true,
    entryDate: "2024-09-27",
    expiryDate: "2024-10-08",
    createdAt: "2024-09-27",
    createdBy: "asd",
    updatedAt: "2024-09-27",
    updatedBy: "asd"
  },
  {
    productId: "p009",
    category: "rau-cu",
    supplier: "Hợp tác xã Hữu Cơ",
    productName: "Củ Dền",
    slug: "cu-den-36mylu",
    description: "Củ dền tươi ngon, thích hợp cho nhiều món ăn bổ dưỡng.",
    price: 27000,
    stock: 70,
    weight: 1,
    unit: "kg",
    origin: "Ninh Bình",
    organic: true,
    images: ["https://placehold.jp/250x192.png"],
    status: true,
    entryDate: "2024-09-26",
    expiryDate: "2024-10-10",
    createdAt: "2024-09-26",
    createdBy: "asd",
    updatedAt: "2024-09-26",
    updatedBy: "asd"
  },
  {
    productId: "p010",
    category: "trai-cay",
    supplier: "Công ty Xuất khẩu Nông sản",
    productName: "Bưởi Da Xanh",
    slug: "buoi-da-xanh-vy0xdz",
    description: "Bưởi da xanh ngọt thanh, không thuốc bảo vệ thực vật.",
    price: 60000,
    stock: 40,
    weight: 1,
    unit: "kg",
    origin: "Bến Tre",
    organic: true,
    images: ["https://placehold.jp/250x192.png"],
    status: true,
    entryDate: "2024-09-25",
    expiryDate: "2024-10-10",
    createdAt: "2024-09-25",
    createdBy: "asd",
    updatedAt: "2024-09-25",
    updatedBy: "asd"
  }
]
